apiVersion: v1
kind: PersistentVolume
metadata:
  name: qlcb-btc-pv
  namespace: qlcb-btc
spec:
  storageClassName: qlcb-btc
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.100.170
    path: /home/2bs/Downloads/pc/application/k8s/volume-data


---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qlcb-btc-pvc
  namespace: qlcb-btc
spec:
  storageClassName: qlcb-btc
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi