apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.harborCredentials.secretName }}
  namespace: {{ .Values.namespaceName | default "qlcb-btc" }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ printf "{\"auths\":{\"%s\":{\"auth\":\"%s\"}}}" .Values.harborCredentials.server (printf "%s:%s" .Values.harborCredentials.username .Values.harborCredentials.password | b64enc) | b64enc }}
